### ISSUE TITLE
[fix notebooks/02-ingestion/02-batch-ingestion.ipynb] Wrong behaviour on nulls ?

### ISSUE THREAD

**Issue by adithyachakilam** [implydata/learn-druid#70]
Not sure if something changed with v28 that should be updated here ?

This is the corresponding change:
https://github.com/implydata/learn-druid/commit/9362b23e7e1b2a37ebf4ab92d2b5dba67da6bb67

before:
<img width="525" alt="Screenshot 2024-02-13 at 11 06 42 PM" src="https://github.com/implydata/learn-druid/assets/35785271/01817d29-7dee-4cdd-affa-c206937e2b76">

after: 

<img width="676" alt="Screenshot 2024-02-13 at 11 06 32 PM" src="https://github.com/implydata/learn-druid/assets/35785271/a6465ec4-19e0-4c01-bc3a-719cb1415ff4">

**Comment by adithyachakilam** [comment]
@sergioferragut Can you please take a look ?

**Comment by petermarshallio** [comment]
Thank you for the spot @adithyachakilam ! Looks like this might be because of the default NULL handling change @sergioferragut ?

**Comment by sergioferragut** [comment]
I'm testing it with 29.0.1 to see if the behavior persists. we've already updated the SQL in the latest version to 
```
SELECT EXTRACT( HOUR FROM "__time") time_hour, city, count(distinct "session") session_count
FROM "example-kttm-transform-batch" 
WHERE "city" IS NOT NULL AND "city" <> ''
GROUP BY 1,2 
ORDER BY 3 DESC 
LIMIT 10
```

which fixes the issue regardless of the NULL handling mode that it is setup to use.
