### ISSUE TITLE
Group By notebook fails to complete

### ISSUE THREAD

**Issue by petermarshallio** [implydata/learn-druid#93]
A large number of cells in http://localhost:8889/lab/tree/03-query/01-groupby.ipynb fail to run as there's an incorrect dimension reference. (Should it be `latest_session_length`?)

**Comment by petermarshallio** [comment]
@hevansDev it looks like this was introduced in https://github.com/implydata/learn-druid/pull/72 when LATEST BY was added to the notebook. @techdocsmith what would you like to do here? I feel like we should revert, and pull LATEST BY / EARLIEST BY somewhere else? Suggestions welcome?

**Comment by techdocsmith** [comment]
@petermarshallio , @hevansDev , I would be OK putting LATEST BY / EARLIEST BY in its own notebook. Possibly some idea for use case here: https://github.com/apache/druid/blob/master/docs/tutorials/tutorial-latest-by.md

**Comment by hevansDev** [comment]
@petermarshallio could do some or all of this work at the same time as adding the examples for GROUP BY COMPLEX

**Comment by petermarshallio** [comment]
This is probably urgent enough to do a fix now IMHO @hevansDev - currently the notebook just doesn't work.
